# checks out, installs node dependencies, runs typecheck, and runs lint
name: CI
env:
  SKIP_ENV_VALIDATION: 1
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - uses: oven-sh/setup-bun@v1
      - name: Install Dependencies
        run: bun install
      - name: Typecheck
        run: npm run typecheck
      - name: Lint
        run: npm run lint
