# checks out, installs node dependencies, runs typecheck, and runs lint
name: CI
env:
  SKIP_ENV_VALIDATION: 1
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # - uses: pnpm/action-setup@v2
      #   with:
      #     version: 8
      - name: Install Dependencies
        run: npm install
      - name: Typecheck
        run: npm run typecheck
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run ci:build
